version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/web
    env_file:
      - .env
  proxy:
    build: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web